### ISSUE TITLE
Mention in slide [ADDITIONAL RESOURCES]

### ISSUE THREAD

**Issue by jsenon** [christian-posta/istio-workshop#13]
In ADDITIONAL RESOURCES repo from Zack is not up to date. Could you link also to following repo:
https://github.com/retroryan/istio-workshop? We have also added aws workshop deployment

**Comment by christian-posta** [comment]
Okay cool, thanks for the heads up. So the link to Zach's repo seems to work. Did you mean the material is not up to date? I can change the link to the retro ryan one or add it.

**Comment by christian-posta** [comment]
Added it https://github.com/christian-posta/istio-workshop/commit/44a2acd9d8013766ebe8b565f2bfb34e4c06b44f

**Comment by jsenon** [comment]
Hi Chrisitan, Sounds good like this because I don't know if Zach Butcher have modified something in his fork. Thanks
